favicon: null
name: davidwells
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.2617021
  brandStrength: 0.2626076613087207
  lightness: 0.6276596
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  rhythmicContrast: 0.3829787
typography_spectrum: 0.3382979
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.63655
analytics:
  twitter: null
  google: null
  facebook: null
